#This script will use the dataframe generated by the script getData.R
#To generate the plot1.png run the script at R terminal
#source("plot1.R")
png("plot1.png",width=480,height=480)
hist(DF$Global_active_power,col="red",main = "Global Active Power", xlab = "Global Active Power (kilowatts)")
dev.off()