#This script will use the dataframe generated by the script getData.R
#To generate the plot4.png run the script at R terminal
#source("plot4.R")
png("plot4.png",width=480,height=480)
par(mfrow=c(2,2))
with(DF,{ 
  plot(DateTime,Global_active_power,type="l",ylab = "Global Active Power")
  plot(DateTime,Voltage,type="l",xlab="datetime")
  plot(DateTime,Sub_metering_1,type="n",ylab = "Energy sub meetering",xlab="")
  points(DateTime,Sub_metering_1,type="l",col="black")
  points(DateTime,Sub_metering_2,type="l",col="red")
  points(DateTime,Sub_metering_3,type="l",col="blue")
  legend("topright",lty = c(1,1,1),col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),bty="n")
  plot(DateTime,Global_reactive_power,type="l",xlab="datetime")
})
dev.off()
