#This script will use the dataframe generated by the script getData.R
#To generate the plot3.png run the script at R terminal
#source("plot3.R")
png("plot3.png",width=480,height=480)
with(DF,plot(DateTime,Sub_metering_1,type="n",ylab = "Energy sub meetering",xlab=""))
with(DF,points(DateTime,Sub_metering_1,type="l",col="black"))
with(DF,points(DateTime,Sub_metering_2,type="l",col="red"))
with(DF,points(DateTime,Sub_metering_3,type="l",col="blue"))
legend("topright",lty = c(1,1,1),col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()