#This script will use the dataframe generated by the script getData.R
#To generate the plot2.png run the script at R terminal
#source("plot2.R")
png("plot2.png",width=480,height=480)
with(DF,plot(DateTime,Global_active_power,type="l",ylab = "Global Active Power (kilowatts)",xlab=""))
dev.off()